### ISSUE TITLE
Hello ,I seemingly lack file

### ISSUE THREAD

**Issue by banzhuanzai1** [edgarschnfld/CADA-VAE-PyTorch#31]
lacking file include awa2_generator and awa2_final_classifier

**Comment by banzhuanzai1** [comment]
Discriminative classifier parameters loaded...
awa2_generator
Traceback (most recent call last):
  File "D:/零次学习/Feature-Generating-Networks/main.py", line 105, in <module>
    success = train_agent.load_model(model=model_name)
  File "D:\零次学习\Feature-Generating-Networks\trainer.py", line 299, in load_model
    raise Exception("Trying to load unknown model: %s" % model)
Exception: Trying to load unknown model: awa2_generator

Process finished with exit code 1
